baseurl = "https://tolikcode.github.io"
languageCode = "en-us"
title = "Tolik Code"
theme = "shiori"
disqusShortname = "tolikcode"
disablePathToLower = "true"

[params]
  github = "tolikcode"
  email = "akrivchenko@outlook.com"
